version: 2.1

jobs:
  build:
    working_directory: ~/frontend-interview-project
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout

      - restore_cache: # Restore the dependency cache
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-

      - run:
          name: Installing dependencies
          command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run lint
          command: npm run lint

      - run:
          name: Run tests
          command: npm t

      - run:
          name: Build storybook
          command: npm run build-storybook

workflows:
  version: 2
  build:
    jobs:
      - build
